name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - mongodb
  - pymongo
  - tornado
  - requests
  - bcrypt
  - cryptography
  - pydantic>=0.20,<0.30
  - mongoengine
  - plotly
  - sqlalchemy>=1.3
  - psycopg2
  - postgresql
  - alembic

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcengine>=0.6.2
  - qcelemental>=0.4.0
