# Configure LGTM for this package

extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3
path_classifiers:
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
    - qcfractal/dashboard/* # Very early state, some conditions forcing LGTM issues
    - qcfractal/alembic/* # One-shot, from templates
  generated:
    - qcfractal/_version.py
queries:
- exclude: py/not-named-self # Blocks Pydantic's @validator not accepting `self` until a better fix can be found
- exclude: py/missing-call-to-init
