"""Changed collections.view_uri from String(100) to String

Revision ID: 4394a07e7390
Revises: a2f76bb7be65
Create Date: 2019-10-08 16:57:50.249402

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4394a07e7390'
down_revision = 'a2f76bb7be65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection',
                    'view_url',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection',
                    'view_url',
                    existing_type=sa.String(),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###
