"""add unique indices to stdout,stderr,error

Revision ID: 49dcbd2f3abd
Revises: 5be555fe9dc0
Create Date: 2021-01-06 10:50:05.273791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49dcbd2f3abd"
down_revision = "5be555fe9dc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_baseresult_error", "base_result", ["error"])
    op.create_unique_constraint("uix_baseresult_stderr", "base_result", ["stderr"])
    op.create_unique_constraint("uix_baseresult_stdout", "base_result", ["stdout"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_baseresult_stdout", "base_result", type_="unique")
    op.drop_constraint("uix_baseresult_stderr", "base_result", type_="unique")
    op.drop_constraint("uix_baseresult_error", "base_result", type_="unique")
    # ### end Alembic commands ###
