"""Fix task queue migration

Revision ID: 914724044e9a
Revises: 1604623c481a
Create Date: 2020-08-28 12:58:37.250300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914724044e9a'
down_revision = '1604623c481a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_waiting_sort', table_name='task_queue')
    op.create_index('ix_task_waiting_sort', 'task_queue', [sa.text('priority desc,  created_on')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_waiting_sort', table_name='task_queue')
    op.create_index('ix_task_waiting_sort', 'task_queue', ['priority', 'created_on'], unique=False)
    # ### end Alembic commands ###
