{% set name = "qcfractalcompute" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv ./{{ name }}

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - versioningit

  run:
    - python >=3.8
    - qcportal ={{ version }}
    - parsl

test:
  imports:
    - qcfractalcompute
  commands:
    - qcfractal-compute-manager --help

about:
  home: https://github.com/MolSSI/QCFractal/
  dev_url: https://github.com/MolSSI/QCFractal/
  doc_url: https://molssi.github.io/QCFractal/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/main/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Distributed worker package for QCArchive
