"""add largebinary storage

Revision ID: 4122a71f7031
Revises: ca9c57c0df8d
Create Date: 2023-01-28 09:29:04.763067

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "4122a71f7031"
down_revision = "ca9c57c0df8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    compressionenum = ENUM(name="compressionenum", create_type=False)
    op.create_table(
        "largebinary_store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("compression_type", compressionenum, nullable=False),
        sa.Column("data_local", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "largebinary_store", "base_record", ["record_id"], ["id"], ondelete="cascade")

    op.execute(sa.text("ALTER TABLE largebinary_store ALTER COLUMN data_local SET STORAGE EXTERNAL"))
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Cannot downgrade")
