"""native files to derive from largebinary

Revision ID: 1a61b3bb1ee4
Revises: 1c46a35bf565
Create Date: 2023-02-08 12:22:48.401847

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1a61b3bb1ee4"
down_revision = "1c46a35bf565"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "native_file", "largebinary_store", ["id"], ["id"], ondelete="cascade")
    op.drop_column("native_file", "compression_level")
    op.drop_column("native_file", "is_text")
    op.drop_column("native_file", "uncompressed_size")
    op.drop_column("native_file", "compression")
    op.drop_column("native_file", "data")

    op.execute(
        sa.text(
            """
    CREATE TRIGGER qca_native_file_delete_lb_tr
    AFTER DELETE ON native_file
    FOR EACH ROW EXECUTE PROCEDURE qca_largebinary_base_delete();
    """
        )
    )

    # Some stuff from migra
    op.execute(sa.text("""alter table native_file alter column "id" drop default"""))
    op.execute(sa.text("""drop sequence if exists native_file_id_seq"""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError("Cannot downgrade")
