"""Init migration of molecule msgpack columns

Revision ID: 9adf25dba3bc
Revises: 35bb042920a3
Create Date: 2025-03-04 21:46:38.943420

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9adf25dba3bc"
down_revision = "35bb042920a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # purely for this migration
    op.add_column("molecule", sa.Column("_migrated_status", postgresql.BOOLEAN(), nullable=True, index=True))

    op.add_column("molecule", sa.Column("symbols_tmp", postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column("molecule", sa.Column("geometry_tmp", postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column("molecule", sa.Column("masses_tmp", postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column("molecule", sa.Column("real_tmp", postgresql.ARRAY(sa.Boolean()), nullable=True))
    op.add_column("molecule", sa.Column("atom_labels_tmp", postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column("molecule", sa.Column("atomic_numbers_tmp", postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column("molecule", sa.Column("mass_numbers_tmp", postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column("molecule", sa.Column("fragments_tmp", postgresql.JSON(), nullable=True))
    op.add_column("molecule", sa.Column("fragment_charges_tmp", postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column("molecule", sa.Column("fragment_multiplicities_tmp", postgresql.ARRAY(sa.Float()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Cannot downgrade")
