"""Add server stats

Revision ID: 7952618c1c43
Revises: 39abe82f389f
Create Date: 2026-05-30 11:41:00.475798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7952618c1c43'
down_revision = '39abe82f389f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('record_count', sa.BigInteger(), nullable=False),
    sa.Column('cpu_hours', sa.Double(), nullable=False),
    sa.Column('record_count_details', sa.JSON(), nullable=False),
    sa.Column('database_size', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )

    op.execute(sa.text("""
         INSERT
         INTO server_stats (date, record_count, cpu_hours, record_count_details, database_size, timestamp)
         SELECT DATE(rch.modified_on) AS date,
                COUNT(*)              AS record_count,
                SUM(
                        COALESCE((rch.provenance ->> 'wall_time')::double precision, 0) *
                        COALESCE((rch.provenance ->> 'nthreads')::double precision, 1)
                ) / 3600.0            AS cpu_hours,
                '{}'::JSON            AS record_count_details,
                0::BIGINT             AS database_size,
                MAX(rch.modified_on)  AS timestamp
         FROM record_compute_history rch
                  INNER JOIN base_record br ON rch.record_id = br.id
         WHERE rch.status = 'complete'
           AND br.status = 'complete'
         GROUP BY DATE(rch.modified_on)
    """))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_stats')
    # ### end Alembic commands ###
