"""update external files desc and proj attach

Revision ID: 865e4be6ef5c
Revises: 39abe82f389f
Create Date: 2026-03-28 10:02:22.436175

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "865e4be6ef5c"
down_revision = "39abe82f389f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE external_file SET description = '' WHERE description IS NULL"))

    op.alter_column("external_file", "description", existing_type=sa.VARCHAR(), nullable=False)

    # From migra
    op.execute(sa.text("alter type externalfiletypeenum rename to externalfiletypeenum__old_version_to_be_dropped;"))
    op.execute(sa.text("create type externalfiletypeenum as enum ('dataset_attachment', 'project_attachment');"))
    op.execute(
        sa.text(
            "alter table external_file alter column file_type type externalfiletypeenum using file_type::text::externalfiletypeenum;"
        )
    )
    op.execute(sa.text("drop type externalfiletypeenum__old_version_to_be_dropped;"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Cannot downgrade")
