{% set name = "qcarchivetesting" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv ./qcarchivetesting

requirements:
  host:
    - python >=3.8

  run:
    - qcfractal ={{ version }}

test:
  imports:
    - qcarchivetesting.helpers

about:
  home: https://github.com/MolSSI/{{ name }}
  dev_url: https://github.com/MolSSI/{{ name }}
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/{{ name }}/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Additional testing fixtures and functions for the QCArchive project
