{% set name = "qcportal" %}
{% set pyproject = load_file_data(name ~ '/pyproject.toml') %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv ./{{ name }}

requirements:
  host:
    - python >=3.8

    # All dependencies in 'requires' under the 'build-system' block
    # of pyproject.toml
    {% for dep in pyproject.get('build-system').get('requires') %}
    - {{ dep }}
    {% endfor %}


  run:
    - numpy
    - msgpack-python
    - requests
    - pyyaml
    - pydantic
    - zstandard

    - qcelemental
    - tabulate

    - tqdm
    - pandas


test:
  imports:
    - qcportal

about:
  home: https://github.com/MolSSI/{{ name }}
  dev_url: https://github.com/MolSSI/{{ name }}
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/{{ name }}/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Python library for interacting with QCArchive/QCFractal servers
