map $http_x_forwarded_host $site_host {
  ""      $host;
  default $http_x_forwarded_host;
}

server {
  listen 80;
  server_name _;

  root /srv;
  index index.html;

  sub_filter "__SITE_ORIGIN__" "https://$site_host";
  sub_filter_once off;

  location = /site.webmanifest {
    default_type application/manifest+json;
  }

  location / {
    try_files $uri /index.html;
  }
}
