{% set name = "qcfractal" %}
{% set pyproject = load_file_data(name ~ '/pyproject.toml') %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv ./{{ name }}

requirements:
  host:
    - python >=3.8

    # All dependencies in 'requires' under the 'build-system' block
    # of pyproject.toml
    {% for dep in pyproject.get('build-system').get('requires') %}
    - {{ dep }}
    {% endfor %}


  run:
    - qcfractalcompute ={{ version }}
    - flask
    - flask-jwt-extended
    - gunicorn
    - bcrypt

    # Storage dependencies
    - sqlalchemy >=1.4
    - alembic
    - psycopg2

    # For access logging
    - geoip2

test:
  imports:
    - qcfractal.snowflake
  commands:
    - qcfractal-server --help

about:
  home: https://github.com/MolSSI/{{ name }}
  dev_url: https://github.com/MolSSI/{{ name }}
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/{{ name }}/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Server for the QCArchive project
