name: qcfractal-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz
    - nbsphinx
    - ipython
    - qcfractal-core
    - autodoc-pydantic

    #- pip:
    #  - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
