import * as qcpTypes from "./PortalTypes";

export function moleculeToSDF(qc: qcpTypes.Molecule): string {
  const natoms = qc.symbols.length;
  const lines: string[] = [];
  const nbonds = qc.connectivity?.length ?? 0;

  lines.push("Generated by QCSchemaToSDF");
  lines.push("  NGL Viewer");
  lines.push("");
  lines.push(`${natoms.toString().padStart(3)}${nbonds.toString().padStart(3)}  0  0  0  0            999 V2000`);

  for (let i = 0; i < natoms; i++) {
    const x = qc.geometry[i * 3 + 0].toFixed(4).padStart(10);
    const y = qc.geometry[i * 3 + 1].toFixed(4).padStart(10);
    const z = qc.geometry[i * 3 + 2].toFixed(4).padStart(10);
    const sym = qc.symbols[i].padEnd(3);
    lines.push(`${x}${y}${z} ${sym} 0  0  0  0  0  0  0  0  0  0  0  0`);
  }

  qc.connectivity?.forEach(bond => {
    const a1 = (bond[0] + 1).toString().padStart(3);
    const a2 = (bond[1] + 1).toString().padStart(3);
    const order = bond[2].toString().padStart(3);
    lines.push(`${a1}${a2}${order}  0  0  0  0`);
  });

  lines.push("M  END");
  lines.push("$$$$");
  return lines.join("\n");
}