name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for tag/version

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package
        shell: bash -l {0}
        working-directory: docs
        run: |
          python -m pip install -r requirements.txt

      - name: Build Documentation
        shell: bash -l {0}
        working-directory: docs
        run: |
          export QCArchiveUsername=${{ secrets.QCARCHIVEUSERNAME }}
          export QCArchivePWD=${{ secrets.QCARCHIVEPWD }}
          cd docs
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name != 'pull_request'
        with:
          folder: docs/build/html
