name: Build and Deploy Docs

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for tag/version

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package
        shell: bash -l {0}
        working-directory: docs
        run: |
          python -m pip install -r requirements.txt

      - name: Build Documentation
        shell: bash -l {0}
        working-directory: docs
        run: |
          cd docs
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name == 'push' && github.repository == 'MolSSI/QCFractal' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/next' )
        with:
          folder: docs/build/html
