name: Split out QCPortal & QCFractalCompute

on:
  push:
    branches:
      - master
      - next
    paths:
      - 'qcportal/**'
      - 'qcfractalcompute/**'

jobs:
  make_subpackages:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'molssi'

    steps:
      - name: Configure git
        shell: bash -e -l {0}
        run: |
            git config --global user.name "QCArchiveBot"
            git config --global user.email "qcarchive@molssi.org"

      - name: Clone the QCFractal repository
        uses: actions/checkout@v3
        with:
            path: QCFractal
            fetch-depth: 0

      - name: Clone the existing QCFractalCompute repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.QCABOT_PAT }}
            repository: MolSSI/QCFractalCompute
            ref: ${{ github.ref_name }}
            path: QCFractalCompute
            fetch-depth: 0

      - name: Clone the existing QCPortal repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.QCABOT_PAT }}
            repository: MolSSI/QCPortal
            ref: ${{ github.ref_name }}
            path: QCPortal
            fetch-depth: 0

      - name: Merge onto QCFractalCompute repo
        shell: bash -e -l {0}
        run: |
            git -C QCFractal subtree split -q --prefix qcfractalcompute --branch __compute_split_tmp
            git -C QCFractalCompute subtree pull --prefix qcfractalcompute ../QCFractal __compute_split_tmp

      - name: Push changes to QCFractalCompute repo
        shell: bash -e -l {0}
        run: |
            git -C QCFractalCompute push origin ${{ github.ref_name }}

      - name: Merge onto QCPortal repo
        shell: bash -e -l {0}
        run: |
            git -C QCFractal subtree split -q --prefix qcportal --branch __portal_split_tmp
            git -C QCPortal subtree pull --prefix qcportal ../QCFractal __portal_split_tmp

      - name: Push changes to QCPortal repo
        shell: bash -e -l {0}
        run: |
            git -C QCPortal push origin ${{ github.ref_name }}
